# NIFTY Universe Data - 60 NSE Indexes
# Last Updated: 2025-12-12
# Source: NSE official indices (from user specification)

# Base stock lists - will be dynamically fetched from NSE cache
# These are placeholders that get populated from nse_universe_cache.json

# All 60 indexes in the specified order
INDEX_NAMES = [
    "NIFTY 50",
    "NIFTY NEXT 50",
    "NIFTY BANK",
    "NIFTY FINANCIAL SERVICES",
    "NIFTY MIDCAP SELECT",
    "NIFTY 100",
    "NIFTY 200",
    "NIFTY 500",
    "NIFTY MIDCAP 50",
    "NIFTY MIDCAP 100",
    "NIFTY MIDCAP 150",
    "NIFTY SMALLCAP 100",
    "NIFTY SMALLCAP 50",
    "NIFTY SMALLCAP 250",
    "NIFTY MIDSMALLCAP 400",
    "NIFTY500 MULTICAP 50:25:25",
    "NIFTY LARGEMIDCAP 250",
    "NIFTY TOTAL MARKET",
    "NIFTY MICROCAP 250",
    "NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED",
    "NIFTY INDIA FPI 150",
    "NIFTY50 DIVIDEND POINTS",
    "NIFTY ALPHA 50",
    "NIFTY50 EQUAL WEIGHT",
    "NIFTY100 EQUAL WEIGHT",
    "NIFTY100 LOW VOLATILITY 30",
    "NIFTY200 QUALITY 30",
    "NIFTY ALPHA LOW-VOLATILITY 30",
    "NIFTY200 MOMENTUM 30",
    "NIFTY MIDCAP150 QUALITY 50",
    "NIFTY200 ALPHA 30",
    "NIFTY MIDCAP150 MOMENTUM 50",
    "NIFTY500 MOMENTUM 50",
    "NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100",
    "NIFTY SMALLCAP250 MOMENTUM QUALITY 100",
    "NIFTY TOP 10 EQUAL WEIGHT",
    "NIFTY ALPHA QUALITY LOW-VOLATILITY 30",
    "NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30",
    "NIFTY HIGH BETA 50",
    "NIFTY LOW VOLATILITY 50",
    "NIFTY QUALITY LOW-VOLATILITY 30",
    "NIFTY SMALLCAP250 QUALITY 50",
    "NIFTY TOP 15 EQUAL WEIGHT",
    "NIFTY100 ALPHA 30",
    "NIFTY200 VALUE 30",
    "NIFTY500 EQUAL WEIGHT",
    "NIFTY500 MULTICAP MOMENTUM QUALITY 50",
    "NIFTY500 VALUE 50",
    "NIFTY TOP 20 EQUAL WEIGHT",
    "NIFTY500 QUALITY 50",
    "NIFTY500 LOW VOLATILITY 50",
    "NIFTY500 MULTIFACTOR MQVLV 50",
    "NIFTY50 USD",
    "NIFTY500 FLEXICAP QUALITY 30",
    "NIFTY TOTAL MARKET MOMENTUM QUALITY 50",
]

# Fallback stock lists for key indexes (used when NSE cache is unavailable)
NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", 
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "HCLTECH",
    "WIPRO", "ULTRACEMCO", "TITAN", "BAJFINANCE", "SUNPHARMA",
    "NESTLEIND", "TECHM", "ONGC", "NTPC", "POWERGRID",
    "M&M", "TATAMOTORS", "TATASTEEL", "ADANIPORTS", "COALINDIA",
    "BAJAJFINSV", "INDUSINDBK", "HINDALCO", "JSWSTEEL", "GRASIM",
    "DIVISLAB", "DRREDDY", "CIPLA", "APOLLOHOSP", "EICHERMOT",
    "HEROMOTOCO", "BRITANNIA", "TATACONSUM", "BAJAJ-AUTO", "SHRIRAMFIN",
    "ADANIENT", "SBILIFE", "HDFCLIFE", "BPCL", "IOC"
]

NIFTY_NEXT_50 = [
    "ADANIGREEN", "ADANIPOWER", "ADANITRANS", "AMBUJACEM", "ATGL",
    "BERGEPAINT", "BEL", "BOSCHLTD", "CANBK", "CHOLAFIN",
    "COLPAL", "DABUR", "DLF", "DMART", "GAIL",
    "GODREJCP", "HAL", "HAVELLS", "ICICIPRULI", "INDIGO",
    "JINDALSTEL", "LTIM", "MARICO", "MOTHERSON", "MPHASIS",
    "NAUKRI", "NMDC", "PAYTM", "PIDILITIND", "PNB",
    "RECLTD", "SAIL", "SBICARD", "SIEMENS", "TATAPOWER",
    "TATATECH", "TORNTPHARM", "TRENT", "TVSMOTOR", "UBL",
    "VEDL", "VOLTAS", "ZOMATO", "ZYDUSLIFE", "ICICIGI",
    "PGHH", "PETRONET", "PFC", "INDHOTEL", "BAJAJHLDNG"
]

NIFTY_BANK = [
    "HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK",
    "INDUSINDBK", "BANDHANBNK", "FEDERALBNK", "PNB", "IDFCFIRSTB",
    "AUBANK", "BANKBARODA"
]

NIFTY_100 = list(dict.fromkeys(NIFTY_50 + NIFTY_NEXT_50))

# Universe dictionary - all 60 indexes
UNIVERSES = {name: [] for name in INDEX_NAMES}

# Populate key fallback lists
UNIVERSES["NIFTY 50"] = NIFTY_50
UNIVERSES["NIFTY NEXT 50"] = NIFTY_NEXT_50
UNIVERSES["NIFTY BANK"] = NIFTY_BANK
UNIVERSES["NIFTY 100"] = NIFTY_100
UNIVERSES["NIFTY FINANCIAL SERVICES"] = list(dict.fromkeys(NIFTY_BANK + ["BAJFINANCE", "BAJAJFINSV", "SBILIFE", "HDFCLIFE", "ICICIGI", "SHRIRAMFIN"]))
UNIVERSES["NIFTY MIDCAP SELECT"] = NIFTY_NEXT_50[:25]
UNIVERSES["NIFTY 200"] = NIFTY_100
UNIVERSES["NIFTY 500"] = NIFTY_100
UNIVERSES["NIFTY MIDCAP 50"] = NIFTY_NEXT_50[:50]
UNIVERSES["NIFTY MIDCAP 100"] = NIFTY_NEXT_50
UNIVERSES["NIFTY MIDCAP 150"] = NIFTY_NEXT_50
UNIVERSES["NIFTY SMALLCAP 100"] = NIFTY_NEXT_50
UNIVERSES["NIFTY SMALLCAP 50"] = NIFTY_NEXT_50[:50]
UNIVERSES["NIFTY SMALLCAP 250"] = NIFTY_100
UNIVERSES["NIFTY MIDSMALLCAP 400"] = NIFTY_100
UNIVERSES["NIFTY500 MULTICAP 50:25:25"] = NIFTY_100
UNIVERSES["NIFTY LARGEMIDCAP 250"] = NIFTY_100
UNIVERSES["NIFTY TOTAL MARKET"] = NIFTY_100
UNIVERSES["NIFTY MICROCAP 250"] = NIFTY_NEXT_50
UNIVERSES["NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED"] = NIFTY_100
UNIVERSES["NIFTY INDIA FPI 150"] = NIFTY_100
UNIVERSES["NIFTY50 DIVIDEND POINTS"] = NIFTY_50[:20]
UNIVERSES["NIFTY ALPHA 50"] = NIFTY_50
UNIVERSES["NIFTY50 EQUAL WEIGHT"] = NIFTY_50
UNIVERSES["NIFTY100 EQUAL WEIGHT"] = NIFTY_100
UNIVERSES["NIFTY100 LOW VOLATILITY 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY200 QUALITY 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY ALPHA LOW-VOLATILITY 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY200 MOMENTUM 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY MIDCAP150 QUALITY 50"] = NIFTY_NEXT_50[:50]
UNIVERSES["NIFTY200 ALPHA 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY MIDCAP150 MOMENTUM 50"] = NIFTY_NEXT_50[:50]
UNIVERSES["NIFTY500 MOMENTUM 50"] = NIFTY_50
UNIVERSES["NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100"] = NIFTY_100
UNIVERSES["NIFTY SMALLCAP250 MOMENTUM QUALITY 100"] = NIFTY_100
UNIVERSES["NIFTY TOP 10 EQUAL WEIGHT"] = NIFTY_50[:10]
UNIVERSES["NIFTY ALPHA QUALITY LOW-VOLATILITY 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY HIGH BETA 50"] = NIFTY_50
UNIVERSES["NIFTY LOW VOLATILITY 50"] = NIFTY_50
UNIVERSES["NIFTY QUALITY LOW-VOLATILITY 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY SMALLCAP250 QUALITY 50"] = NIFTY_NEXT_50[:50]
UNIVERSES["NIFTY TOP 15 EQUAL WEIGHT"] = NIFTY_50[:15]
UNIVERSES["NIFTY100 ALPHA 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY200 VALUE 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY500 EQUAL WEIGHT"] = NIFTY_100
UNIVERSES["NIFTY500 MULTICAP MOMENTUM QUALITY 50"] = NIFTY_50
UNIVERSES["NIFTY500 VALUE 50"] = NIFTY_50
UNIVERSES["NIFTY TOP 20 EQUAL WEIGHT"] = NIFTY_50[:20]
UNIVERSES["NIFTY500 QUALITY 50"] = NIFTY_50
UNIVERSES["NIFTY500 LOW VOLATILITY 50"] = NIFTY_50
UNIVERSES["NIFTY500 MULTIFACTOR MQVLV 50"] = NIFTY_50
UNIVERSES["NIFTY50 USD"] = NIFTY_50
UNIVERSES["NIFTY500 FLEXICAP QUALITY 30"] = NIFTY_50[:30]
UNIVERSES["NIFTY TOTAL MARKET MOMENTUM QUALITY 50"] = NIFTY_50


def _load_nse_cache():
    """Load NSE cache if available."""
    try:
        from pathlib import Path
        import json
        cache_file = Path("nse_universe_cache.json")
        if cache_file.exists():
            with open(cache_file, 'r') as f:
                data = json.load(f)
                return data.get('universes', {})
    except:
        pass
    return {}


def get_universe(name):
    """Get stock list for a given universe name. Uses NSE cache if available."""
    # First try NSE cache
    cached = _load_nse_cache()
    if name in cached and cached[name]:
        return cached[name]
    
    # Fallback to hardcoded
    return UNIVERSES.get(name, [])


def get_all_universe_names():
    """Get all available universe names in the specified order."""
    return INDEX_NAMES.copy()


def get_broad_market_universes():
    """Get broad market indices."""
    return [
        "NIFTY 50", "NIFTY NEXT 50", "NIFTY BANK", "NIFTY FINANCIAL SERVICES",
        "NIFTY MIDCAP SELECT", "NIFTY 100", "NIFTY 200", "NIFTY 500"
    ]


def get_sectoral_universes():
    """Get sectoral/thematic indices (now just a subset of key indexes)."""
    return [
        "NIFTY BANK", "NIFTY FINANCIAL SERVICES", "NIFTY MIDCAP SELECT"
    ]


def get_cap_based_universes():
    """Get cap-based indices."""
    return [
        "NIFTY MIDCAP 50", "NIFTY MIDCAP 100", "NIFTY MIDCAP 150",
        "NIFTY SMALLCAP 50", "NIFTY SMALLCAP 100", "NIFTY SMALLCAP 250",
        "NIFTY MIDSMALLCAP 400", "NIFTY MICROCAP 250"
    ]


def get_thematic_universes():
    """Get strategy/factor indices."""
    return [
        "NIFTY ALPHA 50", "NIFTY HIGH BETA 50", "NIFTY LOW VOLATILITY 50",
        "NIFTY500 MOMENTUM 50", "NIFTY500 QUALITY 50", "NIFTY500 VALUE 50"
    ]
