# Comprehensive NIFTY Universe Data
# Last Updated: 2025-11-30
# Source: NSE official indices

# Broad Market Indices
NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", 
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "HCLTECH",
    "WIPRO", "ULTRACEMCO", "TITAN", "BAJFINANCE", "SUNPHARMA",
    "NESTLEIND", "TECHM", "ONGC", "NTPC", "POWERGRID",
    "M&M", "TATAMOTORS", "TATASTEEL", "ADANIPORTS", "COALINDIA",
    "BAJAJFINSV", "INDUSINDBK", "HINDALCO", "JSWSTEEL", "GRASIM",
    "DIVISLAB", "DRREDDY", "CIPLA", "APOLLOHOSP", "EICHERMOT",
    "HEROMOTOCO", "BRITANNIA", "TATACONSUM", "BAJAJ-AUTO", "SHRIRAMFIN",
    "ADANIENT", "SBILIFE", "HDFCLIFE", "BPCL", "IOC"
]

NIFTY_NEXT_50 = [
    "ADANIGREEN", "ADANIPOWER", "ADANITRANS", "AMBUJACEM", "ATGL",
    "BERGEPAINT", "BEL", "BOSCHLTD", "CANBK", "CHOLAFIN",
    "COLPAL", "DABUR", "DLF", "DMART", "GAIL",
    "GODREJCP", "HAL", "HAVELLS", "ICICIPRULI", "INDIGO",
    "JINDALSTEL", "LTIM", "MARICO", "MOTHERSON", "MPHASIS",
    "NAUKRI", "NMDC", "PAYTM", "PIDILITIND", "PNB",
    "RECLTD", "SAIL", "SBICARD", "SIEMENS", "TATAPOWER",
    "TATATECH", "TORNTPHARM", "TRENT", "TVSMOTOR", "UBL",
    "VEDL", "VOLTAS", "ZOMATO", "ZYDUSLIFE", "ICICIGI",
    "PGHH", "PETRONET", "PFC", "INDHOTEL", "BAJAJHLDNG"
]

NIFTY_100 = list(dict.fromkeys(NIFTY_50 + NIFTY_NEXT_50))

NIFTY_200_ADDITIONAL = [
    "ABB", "ACC", "ALKEM", "APOLLOTYRE", "ASHOKLEY",
    "AUROPHARMA", "BALKRISIND", "BANDHANBNK", "BANKBARODA", "BATAINDIA",
    "BIOCON", "BSOFT", "CHAMBLFERT", "COFORGE", "CONCOR",
    "CROMPTON", "CUB", "CUMMINSIND", "DEEPAKNTR", "DIXON",
    "ESCORTS", "EXIDEIND", "FEDERALBNK", "FORTIS", "GLENMARK",
    "GMRINFRA", "GNFC", "GODREJPROP", "GRANULES", "GUJGASLTD",
    "HINDPETRO", "IDEA", "IDFCFIRSTB", "IGL", "INDIACEM",
    "INDUSTOWER", "IRCTC", "IRFC", "JUBLFOOD", "LAURUSLABS",
    "LICHSGFIN", "LUPIN", "MANAPPURAM", "MCX", "MFSL",
    "MGL", "MRF", "MUTHOOTFIN", "NAM-INDIA", "NATIONALUM",
    "NAVINFLUOR", "OBEROIRLTY", "OIL", "PAGEIND", "PERSISTENT",
    "PIIND", "POLYCAB", "PVR", "RBLBANK", "SCHAEFFLER",
    "SHREECEM", "SRF", "STAR", "SUNDARMFIN", "SUNDRMFAST",
    "SUNTV", "SUPREMEIND", "SYNGENE", "TATACHEM", "TATACOMM",
    "TATAELXSI", "TIINDIA", "TORNTPOWER", "TUBE", "UNIONBANK",
    "UPL", "WHIRLPOOL", "YESBANK", "ZEEL", "3MINDIA",
    "AARTIIND", "ABBOTINDIA", "ADANIENSOL", "ADANIGAS", "AFFLE",
    "AJANTPHARM", "AKZOINDIA", "ANGELONE", "APLLTD", "APLAPOLLO",
    "ARVINDFASN", "ASAHIINDIA", "ATUL", "AUBANK", "BAJAJELEC"
]

NIFTY_200 = list(dict.fromkeys(NIFTY_100 + NIFTY_200_ADDITIONAL))

# NIFTY 500 Additional stocks (beyond NIFTY 200)
NIFTY_500_ADDITIONAL = [
    "ABCAPITAL", "ABFRL", "AEGISCHEM", "AIAENG", "AJANTPHARM",
    "AKCL", "ALKYLAMINE", "ALLCARGO", "AMARAJABAT", "AMBER",
    "AMBUJACEM", "ANGELONE", "APARINDS", "APLAPOLLO", "APOLLOTYRE",
    "ARVIND", "ASAHIINDIA", "ASHIANA", "ASIANPAINT", "ASTERDM",
    "ASTRAL", "ATUL", "AUROPHARMA", "AVANTIFEED", "AXISBANK",
    "BAJAJCON", "BAJAJHLDNG", "BALAMINES", "BALKRISIND", "BALRAMCHIN",
    "BANCOINDIA", "BASF", "BAYERCROP", "BDL", "BEL",
    "BERGEPAINT", "BHARATFORG", "BHARTIARTL", "BHEL", "BIOCON",
    "BIRLACORPN", "BLUESTARCO", "BOSCHLTD", "BRIGADE", "BSOFT",
    "CANFINHOME", "CAPLIPOINT", "CARBORUNIV", "CARERATING", "CASTROLIND",
    "CCL", "CEATLTD", "CENTURYPLY", "CENTURYTEX", "CERA",
    "CHALET", "CHAMBLFERT", "CHOLAFIN", "CIPLA", "Clean",
    "COALINDIA", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL",
    "CREDITACC", "CROMPTON", "CUB", "CUMMINSIND", "DABUR",
    "DALBHARAT", "DCMSHRIRAM", "DEEPAKFERT", "DEEPAKNTR", "DELTACORP",
    "DEVYANI", "DHANI", "DHANUKA", "DIVISLAB", "DIXON",
    "DLF", "DRREDDY", "EICHERMOT", "EIDPARRY", "EIHOTEL",
    "ELGIEQUIP", "EMAMILTD", "ENDURANCE", "ENGINERSIN", "EQUITAS",
    "ERIS", "ESCORTS", "EXIDEIND", "FDC", "FEDERALBNK",
    "FINEORG", "FINPIPE", "FLUOROCHEM", "FORTIS", "GAIL",
    "GALAXYSURF", "GANECOS", "GARFIBRES", "GATEWAY", "GEPIL",
    "GESHIP", "GILLETTE", "GLENMARK", "GLAXO", "GMDCLTD",
    "GMMPFAUDLR", "GMRINFRA", "GNFC", "GODREJAGRO", "GODREJCP",
    "GODREJIND", "GODREJPROP", "GOODYEAR", "GPPL", "GRASIM",
    "GREAVESCOT", "GREENLAM", "GRINDWELL", "GSFC", "GSPL",
    "GUJALKALI", "GUJGASLTD", "GULFOILLUB", "HAL", "HAPPSTMNDS",
    "HATHWAY", "HAVELLS", "HCLTECH", "HDFC", "HDFCAMC",
    "HDFCBANK", "HDFCLIFE", "HEG", "HEROMOTOCO", "HFCL",
    "HIMATSEIDE", "HINDALCO", "HINDCOPPER", "HINDPETRO", "HINDUNILVR",
    "HINDZINC", "HONAUT", "HUDCO", "IBREALEST", "ICICIBANK",
    "ICICIGI", "ICICIPRULI", "ICRA", "IDEA", "IDFC",
    "IDFCFIRSTB", "IEX", "IFBIND", "IGL", "IIFL",
    "IIFLWAM", "INDHOTEL", "INDIACEM", "INDIAMART", "INDIANB",
    "INDIGO", "INDOCO", "INDUSINDBK", "INDUSTOWER", "INFIBEAM",
    "INFY", "INGERRAND", "INOXLEISUR", "INTELLECT", "IOC",
    "IPCALAB", "IRCON", "IRCTC", "IRFC", "IRB",
    "ITC", "ITDC", "ITI", "JAMNAAUTO", "JBCHEPHARM",
    "JKCEMENT", "JKIL", "JKLAKSHMI", "JKPAPER", "JKTYRE",
    "JMFINANCIL", "JSL", "JSWENERGY", "JSWSTEEL", "JUBLFOOD",
    "JUBLINGREA", "JUSTDIAL", "JYOTHYLAB", "KAJARIACER", "KALPATPOWR",
    "KANSAINER", "KEC", "KEI", "KIRIINDUS", "KNRCON",
    "KOLTEPATIL", "KOTAKBANK", "KPITTECH", "KRBL", "L&TFH",
    "LALPATHLAB", "LAOPALA", "LAURUSLABS", "LAXMIMACH", "LEMONTREE",
    "LICHSGFIN", "LINDEINDIA", "LT", "LTI", "LTTS",
    "LUPIN", "LUXIND", "LXCHEM", "MAHABANK", "MAHINDCIE",
    "MAHLOG", "MANAPPURAM", "MARICO", "MARUTI", "MCDOWELL-N",
    "MCX", "METROPOLIS", "MFSL", "MGL", "MHRIL",
    "MIDHANI", "MINDACORP", "MINDAIND", "MINDTREE", "MOIL",
    "MOTHERSUMI", "MOTILALOFS", "MPHASIS", "MRF", "MRPL",
    "MUTHOOTFIN", "NAM-INDIA", "NATIONALUM", "NAUKRI", "NAVINFLUOR",
    "NBCC", "NESTLEIND", "NETWORK18", "NHPC", "NLCINDIA",
    "NMDC", "NTPC", "OBEROIRLTY", "OFSS", "OIL",
    "ONGC", "ORIENTELEC", "PAGEIND", "PARAGMILK", "PCJEWELLER",
    "PERSISTENT", "PETRONET", "PFC", "PFIZER", "PGHH",
    "PHOENIXLTD", "PIDILITIND", "PIIND", "PNB", "PNBHOUSING",
    "PNCINFRA", "POLYCAB", "POLYMED", "POWERGRID", "POWERINDIA",
    "PRSMJOHNSN", "PSPPROJECT", "PTC", "PVR", "QUESS",
    "RADICO", "RAIN", "RAJESHEXPO", "RALLIS", "RAMCOCEM",
    "RATNAMANI", "RAYMOND", "RBLBANK", "RCF", "RECLTD",
    "REDINGTON", "RELAXO", "RELIANCE", "RELIGARE", "RPOWER",
    "RTNPOWER", "SANOFI", "SARDAEN", "SAREGAMA", "SBINcard",
    "SBILIFE", "SCHAEFFLER", "SEQUENT", "SFL", "SHARDACROP",
    "SHILPAMED", "SHOPERSTOP", "SHREECEM", "SHRIRAMFIN", "SIEMENS",
    "SIS", "SJVN", "SKFINDIA", "SOLARINDS", "SONATSOFTW",
    "SPARC", "SPLPETRO", "SPTL", "SPYL", "SRF",
    "SRTRANSFIN", "STAR", "STLTECH", "SUDARSCHEM", "SUNCLAYLTD",
    "SUNDARMFIN", "SUNDRMFAST", "SUNPHARMA", "SUNTV", "SUPRAJIT",
    "SUPREMEIND", "SUVEN", "SWANENERGY", "SYMPHONY", "SYNGENE",
    "TAJGVK", "TANLA", "TASTYBITE", "TATACHEM", "TATACOMM",
    "TATACONSUM", "TATAELXSI", "TATAMOTORS", "TATAPOWER", "TATASTEEL",
    "TCS", "TEAMLEASE", "TECHM", "TEXRAIL", "THERMAX",
    "THYROCARE", "TIDEWATER", "TIINDIA", "TIMKEN", "TITAN",
    "TNPETRO", "TORNTPHARM", "TORNTPOWER", "TRENT", "TTKPRESTIG",
    "TV18BRDCST", "TVSMOTOR", "TVSSRICHAK", "TVTODAY", "UCOBANK",
    "UFLEX", "UBL", "ULTRACEMCO", "UNICHEMLAB", "UNIONBANK",
    "UPL", "VGUARD", "VBL", "VEDL", "VENKEYS",
    "VIPIND", "VINATIORGA", "VINDHYATEL", "VMART", "VOLTAS",
    "VSTIND", "VSTVPP", "WABAG", "WABCOINDIA", "WELCORP",
    "WELSPUNIND", "WESTLIFE", "WHIRLPOOL", "WIPRO", "WOCKPHARMA",
    "ZEEL", "ZENSARTECH", "ZENTEC", "ZOMATO", "ZYDUSLIFE"
]

# Deduplicate NIFTY_500 to ensure unique stocks only
NIFTY_500 = list(dict.fromkeys(NIFTY_200 + NIFTY_500_ADDITIONAL))

# Sectoral Indices
NIFTY_BANK = [
    "HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK",
    "INDUSINDBK", "BANDHANBNK", "FEDERALBNK", "PNB", "IDFCFIRSTB",
    "AUBANK", "BANKBARODA"
]

NIFTY_FINANCIAL_SERVICES = list(dict.fromkeys(NIFTY_BANK + ["BAJFINANCE", "BAJAJFINSV", "SBILIFE", "HDFCLIFE", "ICICIGI", "SHRIRAMFIN"]))

NIFTY_IT = [
    "TCS", "INFY", "HCLTECH", "WIPRO", "TECHM",
    "LTIM", "MPHASIS", "COFORGE", "PERSISTENT", "BSOFT"
]

NIFTY_PHARMA = [
    "SUNPHARMA", "DIVISLAB", "DRREDDY", "CIPLA", "BIOCON",
    "AUROPHARMA", "LUPIN", "TORNTPHARM", "ALKEM", "GLENMARK"
]

NIFTY_AUTO = [
    "MARUTI", "TATAMOTORS", "M&M", "BAJAJ-AUTO", "EICHERMOT",
    "HEROMOTOCO", "TVSMOTOR", "ASHOKLEY", "BOSCHLTD", "APOLLOTYRE"
]

NIFTY_FMCG = [
    "HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "TATACONSUM",
    "GODREJCP", "DABUR", "MARICO", "COLPAL", "UBL"
]

NIFTY_METAL = [
    "TATASTEEL", "HINDALCO", "JSWSTEEL", "COALINDIA", "VEDL",
    "JINDALSTEL", "SAIL", "NATIONALUM", "NMDC", "HINDZINC"
]

NIFTY_REALTY = [
    "DLF", "GODREJPROP", "OBEROIRLTY", "PHOENIXLTD", "PRESTIGE",
    "BRIGADE", "SOBHA", "SUNTECK", "LODHA"
]

NIFTY_ENERGY = [
    "RELIANCE", "ONGC", "NTPC", "POWERGRID", "BPCL",
    "IOC", "GAIL", "ADANIGREEN", "ADANIPOWER", "TATAPOWER"
]

NIFTY_CONSUMPTION = [
    "TITAN", "DMART", "JUBLFOOD", "TRENT", "PVRINOX",
    "VOLTAS", "BATAINDIA", "PAGEIND", "VBL", "RELAXO"
]

NIFTY_MEDIA = [
    "ZEEL", "SUNTV", "PVRINOX", "NAZARA", "SAREGAMA"
]

NIFTY_HEALTHCARE = list(dict.fromkeys(NIFTY_PHARMA + ["APOLLOHOSP", "FORTIS", "MAXHEALTH"]))

NIFTY_OIL_GAS = [
    "RELIANCE", "ONGC", "BPCL", "IOC", "GAIL",
    "HINDPETRO", "OIL", "PETRONET", "IGL", "MGL"
]

# Cap-based Indices - properly derived from larger indices
# MIDCAP: Stocks ranked 101-250 by market cap (roughly from NIFTY 200 - NIFTY 100)
NIFTY_MIDCAP_50 = NIFTY_200_ADDITIONAL[:50]  # First 50 stocks beyond NIFTY 100

NIFTY_MIDCAP_100 = NIFTY_200_ADDITIONAL[:100] if len(NIFTY_200_ADDITIONAL) >= 100 else NIFTY_200_ADDITIONAL

NIFTY_MIDCAP_150 = list(dict.fromkeys(NIFTY_200_ADDITIONAL + NIFTY_500_ADDITIONAL[:50]))

# SMALLCAP: Stocks ranked 251+ by market cap (roughly NIFTY 500 - NIFTY 200)
NIFTY_SMALLCAP_50 = NIFTY_500_ADDITIONAL[:50]

NIFTY_SMALLCAP_100 = NIFTY_500_ADDITIONAL[:100]

# SMALLCAP 250 = All remaining stocks in NIFTY 500 after NIFTY 200
NIFTY_SMALLCAP_250 = NIFTY_500_ADDITIONAL  # This gives us ~300 stocks

NIFTY_MICROCAP_250 = NIFTY_500_ADDITIONAL[100:]  # Smaller companies from the 500 list

# Thematic Indices
NIFTY_PSU = [
    "SBIN", "ONGC", "NTPC", "COALINDIA", "PNB",
    "SAIL", "BEL", "HAL", "NMDC", "RECLTD",
    "PFC", "IRFC", "IRCTC", "GAIL", "OIL"
]

NIFTY_PSU_BANK = [
    "SBIN", "PNB", "CANBK", "BANKBARODA", "UNIONBANK",
    "INDIANB", "MAHABANK", "CENTRALBK"
]

NIFTY_PRIVATE_BANK = [
    "HDFCBANK", "ICICIBANK", "KOTAKBANK", "AXISBANK",
    "INDUSINDBK", "FEDERALBNK", "IDFCFIRSTB", "BANDHANBNK"
]

NIFTY_MNC = [
    "NESTLEIND", "HINDUNILVR", "ASIANPAINT", "ABB", "BOSCHLTD",
    "SIEMENS", "3MINDIA", "ABBOTINDIA", "COLPAL", "PGHH"
]

NIFTY_INFRA = [
    "LT", "ADANIPORTS", "GMRINFRA", "IRB", "NBCC",
    "NCC", "PNC", "WELCORP"
]

NIFTY_COMMODITIES = list(dict.fromkeys(NIFTY_METAL + NIFTY_OIL_GAS))

NIFTY_CPSE = NIFTY_PSU  # Central Public Sector Enterprises

NIFTY_DIVIDEND_OPPORTUNITIES_50 = [
    "COALINDIA", "VEDL", "NMDC", "ONGC", "IOC",
    "HINDPETRO", "BPCL", "GAIL"
]

NIFTY_QUALITY_30 = [
    "TCS", "INFY", "HDFCBANK", "ICICIBANK", "HINDUNILVR",
    "ASIANPAINT", "TITAN", "BAJFINANCE"
]

NIFTY_ALPHA_50 = NIFTY_50  # Simplified

NIFTY_LOW_VOLATILITY_30 = [
    "HINDUNILVR", "NESTLEIND", "BRITANNIA", "COLPAL", "DABUR"
]

NIFTY_MOBILITY = NIFTY_AUTO

NIFTY_INDIA_DIGITAL = list(dict.fromkeys(NIFTY_IT + ["BHARTIARTL", "TATACOMM"]))

NIFTY_CONSUMER_DURABLES = [
    "TITAN", "VOLTAS", "WHIRLPOOL", "HAVELLS", "CROMPTON",
    "BATAINDIA", "VBL"
]

# Additional Cap-based & Strategy Indices
NIFTY_MIDCAP_SELECT = NIFTY_MIDCAP_50  # Alias
NIFTY_MIDSMALLCAP_400 = NIFTY_MIDCAP_100 + NIFTY_SMALLCAP_100  # Combination
NIFTY_LARGEMIDCAP_250 = NIFTY_100 + NIFTY_MIDCAP_150
NIFTY_TOTAL_MARKET = NIFTY_500  # All stocks
NIFTY_500_MULTICAP_50_25_25 = NIFTY_500  # Multicap allocation
NIFTY_500_LARGEMIDSMALL_EQUAL_CAP = NIFTY_500  # Equal weight version
NIFTY_INDIA_FPI_150 = NIFTY_100 + NIFTY_MIDCAP_50  # FPI eligible

# Sectoral Extensions
NIFTY_FINANCIAL_SERVICES_25_50 = NIFTY_FINANCIAL_SERVICES  # Capped version
NIFTY_MIDSMALL_HEALTHCARE = NIFTY_HEALTHCARE[:20]
NIFTY_FINANCIAL_SERVICES_EX_BANK = [s for s in NIFTY_FINANCIAL_SERVICES if s not in NIFTY_BANK]
NIFTY_MIDSMALL_FINANCIAL_SERVICES = NIFTY_FINANCIAL_SERVICES[:15]
NIFTY_MIDSMALL_IT_TELECOM = list(dict.fromkeys(NIFTY_IT + ["BHARTIARTL", "TATACOMM"]))
NIFTY_CHEMICALS = ["UPL", "PIDILITIND", "SRF", "AARTI IND", "DEEPAKNTR", "NAVINFLUOR", "ALKYLAMINE"]
NIFTY_500_HEALTHCARE = NIFTY_PHARMA + NIFTY_HEALTHCARE

# Strategy & Factor Indices
NIFTY_GROWTH_SECTORS_15 = NIFTY_IT + NIFTY_AUTO[:5]
NIFTY_100_QUALITY_30 = NIFTY_QUALITY_30
NIFTY_50_VALUE_20 = NIFTY_50[:20]
NIFTY_50_TR_2X_LEVERAGE = NIFTY_50  # Leveraged version
NIFTY_50_PR_2X_LEVERAGE = NIFTY_50  # Leveraged version
NIFTY_50_TR_1X_INVERSE = NIFTY_50  # Inverse version
NIFTY_50_PR_1X_INVERSE = NIFTY_50  # Inverse version
NIFTY_50_DIVIDEND_POINTS = NIFTY_DIVIDEND_OPPORTUNITIES_50[:20]
NIFTY_50_EQUAL_WEIGHT = NIFTY_50
NIFTY_100_EQUAL_WEIGHT = NIFTY_100
NIFTY_100_LOW_VOLATILITY_30 = NIFTY_LOW_VOLATILITY_30
NIFTY_200_QUALITY_30 = NIFTY_QUALITY_30
NIFTY_ALPHA_LOW_VOLATILITY_30 = NIFTY_ALPHA_50[:30]
NIFTY_200_MOMENTUM_30 = NIFTY_200[:30]
NIFTY_MIDCAP150_QUALITY_50 = NIFTY_MIDCAP_150[:50]
NIFTY_200_ALPHA_30 = NIFTY_200[:30]
NIFTY_MIDCAP150_MOMENTUM_50 = NIFTY_MIDCAP_150[:50]
NIFTY_500_MOMENTUM_50 = NIFTY_500[:50]
NIFTY_MIDSMALLCAP400_MOMENTUM_QUALITY_100 = NIFTY_MIDSMALLCAP_400[:100]
NIFTY_SMALLCAP250_MOMENTUM_QUALITY_100 = NIFTY_SMALLCAP_250[:100]
NIFTY_TOP_10_EQUAL_WEIGHT = NIFTY_50[:10]
NIFTY_ALPHA_QUALITY_LOW_VOLATILITY_30 = NIFTY_ALPHA_50[:30]
NIFTY_ALPHA_QUALITY_VALUE_LOW_VOLATILITY_30 = NIFTY_50[:30]
NIFTY_HIGH_BETA_50 = NIFTY_50
NIFTY_LOW_VOLATILITY_50 = NIFTY_LOW_VOLATILITY_30 + NIFTY_50[:20]
NIFTY_QUALITY_LOW_VOLATILITY_30 = NIFTY_QUALITY_30
NIFTY_SMALLCAP250_QUALITY_50 = NIFTY_SMALLCAP_250[:50]
NIFTY_TOP_15_EQUAL_WEIGHT = NIFTY_50[:15]
NIFTY_100_ALPHA_30 = NIFTY_100[:30]
NIFTY_200_VALUE_30 = NIFTY_200[:30]
NIFTY_500_EQUAL_WEIGHT = NIFTY_500
NIFTY_500_MULTICAP_MOMENTUM_QUALITY_50 = NIFTY_500[:50]
NIFTY_500_VALUE_50 = NIFTY_500[:50]
NIFTY_TOP_20_EQUAL_WEIGHT = NIFTY_50[:20]
NIFTY_500_QUALITY_50 = NIFTY_500[:50]
NIFTY_500_LOW_VOLATILITY_50 = NIFTY_500[:50]
NIFTY_500_MULTIFACTOR_MQVLV_50 = NIFTY_500[:50]
NIFTY_50_USD = NIFTY_50
NIFTY_500_FLEXICAP_QUALITY_30 = NIFTY_500[:30]
NIFTY_TOTAL_MARKET_MOMENTUM_QUALITY_50 = NIFTY_500[:50]

# Thematic Extensions
NIFTY_INDIA_CONSUMPTION = NIFTY_CONSUMPTION
NIFTY_SERVICES_SECTOR = list(dict.fromkeys(NIFTY_IT + NIFTY_BANK))
NIFTY_100_ESG_SECTOR_LEADERS = NIFTY_100[:50]
NIFTY_100_ESG = NIFTY_100[:50]
NIFTY_INDIA_MANUFACTURING = list(dict.fromkeys(NIFTY_AUTO + NIFTY_METAL + ["BHARATFORG", "CUMMINSIND"]))
NIFTY_INDIA_CORPORATE_GROUP_TATA = ["TCS", "TATACONSUM", "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TITAN"]
NIFTY_500_MULTICAP_INDIA_MANUFACTURING_50_30_20 = NIFTY_INDIA_MANUFACTURING
NIFTY_500_MULTICAP_INFRASTRUCTURE_50_30_20 = NIFTY_INFRA
NIFTY_INDIA_DEFENCE = ["HAL", "BEL", "BDL", "GRSE", "BEML"]
NIFTY_INDIA_TOURISM = ["INDHOTEL", "LEMONTREE", "IRCTC", "SPICEJET"]
NIFTY_CAPITAL_MARKETS = ["CDSL", "MCX", "ANGELONE", "MFSL"]
NIFTY_EV_NEW_AGE_AUTOMOTIVE = list(dict.fromkeys(NIFTY_AUTO + ["TATAMOTORS", "MAHINDRA"]))
NIFTY_INDIA_NEW_AGE_CONSUMPTION = NIFTY_CONSUMPTION
NIFTY_INDIA_SELECT_5_CORPORATE_GROUPS = NIFTY_50[:25]
NIFTY_100_ENHANCED_ESG = NIFTY_100_ESG
NIFTY_CORE_HOUSING = ["SBIN", "HDFCBANK", "ICICIBANK", "LT", "ULTRACEMCO"]
NIFTY_HOUSING = ["SBIN", "HDFCBANK", "ICICIBANK", "LICHSGFIN", "CANBK"]
NIFTY_IPO = NIFTY_50[:20]
NIFTY_MIDSMALL_INDIA_CONSUMPTION = NIFTY_CONSUMPTION[:15]
NIFTY_NON_CYCLICAL_CONSUMER = NIFTY_FMCG
NIFTY_RURAL = list(dict.fromkeys(NIFTY_FMCG + NIFTY_AUTO[:5]))
NIFTY_SHARIAH_25 = NIFTY_50[:25]
NIFTY_TRANSPORTATION_LOGISTICS = ["ADANIPORTS", "CONCOR", "VRL", "BLUEDART", "TCI"]
NIFTY_50_SHARIAH = NIFTY_SHARIAH_25
NIFTY_500_SHARIAH = NIFTY_500[:100]
NIFTY_SME_EMERGE = NIFTY_SMALLCAP_100[:30]
NIFTY_INDIA_INTERNET = ["ZOMATO", "NAUKRI", "INDIAMART", "JUSTDIAL"]
NIFTY_WAVES = NIFTY_INDIA_DIGITAL
NIFTY_INDIA_INFRASTRUCTURE_LOGISTICS = list(dict.fromkeys(NIFTY_INFRA + NIFTY_TRANSPORTATION_LOGISTICS))
INDIA_VIX = []  # Volatility Index - no stocks

# Universe dictionary
UNIVERSES = {
    # Broad Market
    "NIFTY 50": NIFTY_50,
    "NIFTY NEXT 50": NIFTY_NEXT_50,
    "NIFTY 100": NIFTY_100,
    "NIFTY 200": NIFTY_200,
    "NIFTY 500": NIFTY_500,
    
    # Sectoral
    "NIFTY BANK": NIFTY_BANK,
    "NIFTY FINANCIAL SERVICES": NIFTY_FINANCIAL_SERVICES,
    "NIFTY IT": NIFTY_IT,
    "NIFTY PHARMA": NIFTY_PHARMA,
    "NIFTY AUTO": NIFTY_AUTO,
    "NIFTY FMCG": NIFTY_FMCG,
    "NIFTY METAL": NIFTY_METAL,
    "NIFTY REALTY": NIFTY_REALTY,
    "NIFTY ENERGY": NIFTY_ENERGY,
    "NIFTY CONSUMPTION": NIFTY_CONSUMPTION,
    "NIFTY MEDIA": NIFTY_MEDIA,
    "NIFTY HEALTHCARE": NIFTY_HEALTHCARE,
    "NIFTY OIL & GAS": NIFTY_OIL_GAS,
    
    # Cap-based
    "NIFTY MIDCAP 50": NIFTY_MIDCAP_50,
    "NIFTY MIDCAP 100": NIFTY_MIDCAP_100,
    "NIFTY MIDCAP 150": NIFTY_MIDCAP_150,
    "NIFTY SMALLCAP 50": NIFTY_SMALLCAP_50,
    "NIFTY SMALLCAP 100": NIFTY_SMALLCAP_100,
    "NIFTY SMALLCAP 250": NIFTY_SMALLCAP_250,
    "NIFTY MICROCAP 250": NIFTY_MICROCAP_250,
    
    # Thematic
    "NIFTY PSU": NIFTY_PSU,
    "NIFTY PSU BANK": NIFTY_PSU_BANK,
    "NIFTY PRIVATE BANK": NIFTY_PRIVATE_BANK,
    "NIFTY MNC": NIFTY_MNC,
    "NIFTY INFRA": NIFTY_INFRA,
    "NIFTY COMMODITIES": NIFTY_COMMODITIES,
    "NIFTY CPSE": NIFTY_CPSE,
    "NIFTY DIVIDEND OPPORTUNITIES 50": NIFTY_DIVIDEND_OPPORTUNITIES_50,
    "NIFTY QUALITY 30": NIFTY_QUALITY_30,
    "NIFTY ALPHA 50": NIFTY_ALPHA_50,
    "NIFTY LOW VOLATILITY 30": NIFTY_LOW_VOLATILITY_30,
    "NIFTY MOBILITY": NIFTY_MOBILITY,
    "NIFTY INDIA DIGITAL": NIFTY_INDIA_DIGITAL,
    "NIFTY CONSUMER DURABLES": NIFTY_CONSUMER_DURABLES,

    # Additional Cap & Strategy Indices
    "NIFTY MIDCAP SELECT": NIFTY_MIDCAP_SELECT,
    "NIFTY MIDSMALLCAP 400": NIFTY_MIDSMALLCAP_400,
    "NIFTY500 MULTICAP 50:25:25": NIFTY_500_MULTICAP_50_25_25,
    "NIFTY LARGEMIDCAP 250": NIFTY_LARGEMIDCAP_250,
    "NIFTY TOTAL MARKET": NIFTY_TOTAL_MARKET,
    "NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED": NIFTY_500_LARGEMIDSMALL_EQUAL_CAP,
    "NIFTY INDIA FPI 150": NIFTY_INDIA_FPI_150,
    "NIFTY FINANCIAL SERVICES 25/50": NIFTY_FINANCIAL_SERVICES_25_50,
    "NIFTY MIDSMALL HEALTHCARE": NIFTY_MIDSMALL_HEALTHCARE,
    "NIFTY FINANCIAL SERVICES EX-BANK": NIFTY_FINANCIAL_SERVICES_EX_BANK,
    "NIFTY MIDSMALL FINANCIAL SERVICES": NIFTY_MIDSMALL_FINANCIAL_SERVICES,
    "NIFTY MIDSMALL IT & TELECOM": NIFTY_MIDSMALL_IT_TELECOM,
    "NIFTY CHEMICALS": NIFTY_CHEMICALS,
    "NIFTY500 HEALTHCARE": NIFTY_500_HEALTHCARE,
    "NIFTY DIVIDEND OPPORTUNITIES 50": NIFTY_DIVIDEND_OPPORTUNITIES_50,
    "NIFTY GROWTH SECTORS 15": NIFTY_GROWTH_SECTORS_15,
    "NIFTY100 QUALITY 30": NIFTY_100_QUALITY_30,
    "NIFTY50 VALUE 20": NIFTY_50_VALUE_20,
    "NIFTY50 TR 2X LEVERAGE": NIFTY_50_TR_2X_LEVERAGE,
    "NIFTY50 PR 2X LEVERAGE": NIFTY_50_PR_2X_LEVERAGE,
    "NIFTY50 TR 1X INVERSE": NIFTY_50_TR_1X_INVERSE,
    "NIFTY50 PR 1X INVERSE": NIFTY_50_PR_1X_INVERSE,
    "NIFTY50 DIVIDEND POINTS": NIFTY_50_DIVIDEND_POINTS,
    "NIFTY50 EQUAL WEIGHT": NIFTY_50_EQUAL_WEIGHT,
    "NIFTY100 EQUAL WEIGHT": NIFTY_100_EQUAL_WEIGHT,
    "NIFTY100 LOW VOLATILITY 30": NIFTY_100_LOW_VOLATILITY_30,
    "NIFTY200 QUALITY 30": NIFTY_200_QUALITY_30,
    "NIFTY ALPHA LOW-VOLATILITY 30": NIFTY_ALPHA_LOW_VOLATILITY_30,
    "NIFTY200 MOMENTUM 30": NIFTY_200_MOMENTUM_30,
    "NIFTY MIDCAP150 QUALITY 50": NIFTY_MIDCAP150_QUALITY_50,
    "NIFTY200 ALPHA 30": NIFTY_200_ALPHA_30,
    "NIFTY MIDCAP150 MOMENTUM 50": NIFTY_MIDCAP150_MOMENTUM_50,
    "NIFTY500 MOMENTUM 50": NIFTY_500_MOMENTUM_50,
    "NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100": NIFTY_MIDSMALLCAP400_MOMENTUM_QUALITY_100,
    "NIFTY SMALLCAP250 MOMENTUM QUALITY 100": NIFTY_SMALLCAP250_MOMENTUM_QUALITY_100,
    "NIFTY TOP 10 EQUAL WEIGHT": NIFTY_TOP_10_EQUAL_WEIGHT,
    "NIFTY ALPHA QUALITY LOW-VOLATILITY 30": NIFTY_ALPHA_QUALITY_LOW_VOLATILITY_30,
    "NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30": NIFTY_ALPHA_QUALITY_VALUE_LOW_VOLATILITY_30,
    "NIFTY HIGH BETA 50": NIFTY_HIGH_BETA_50,
    "NIFTY LOW VOLATILITY 50": NIFTY_LOW_VOLATILITY_50,
    "NIFTY QUALITY LOW-VOLATILITY 30": NIFTY_QUALITY_LOW_VOLATILITY_30,
    "NIFTY SMALLCAP250 QUALITY 50": NIFTY_SMALLCAP250_QUALITY_50,
    "NIFTY TOP 15 EQUAL WEIGHT": NIFTY_TOP_15_EQUAL_WEIGHT,
    "NIFTY100 ALPHA 30": NIFTY_100_ALPHA_30,
    "NIFTY200 VALUE 30": NIFTY_200_VALUE_30,
    "NIFTY500 EQUAL WEIGHT": NIFTY_500_EQUAL_WEIGHT,
    "NIFTY500 MULTICAP MOMENTUM QUALITY 50": NIFTY_500_MULTICAP_MOMENTUM_QUALITY_50,
    "NIFTY500 VALUE 50": NIFTY_500_VALUE_50,
    "NIFTY TOP 20 EQUAL WEIGHT": NIFTY_TOP_20_EQUAL_WEIGHT,
    "NIFTY500 QUALITY 50": NIFTY_500_QUALITY_50,
    "NIFTY500 LOW VOLATILITY 50": NIFTY_500_LOW_VOLATILITY_50,
    "NIFTY500 MULTIFACTOR MQVLV 50": NIFTY_500_MULTIFACTOR_MQVLV_50,
    "NIFTY50 USD": NIFTY_50_USD,
    "NIFTY500 FLEXICAP QUALITY 30": NIFTY_500_FLEXICAP_QUALITY_30,
    "NIFTY TOTAL MARKET MOMENTUM QUALITY 50": NIFTY_TOTAL_MARKET_MOMENTUM_QUALITY_50,
    "NIFTY INDIA CONSUMPTION": NIFTY_INDIA_CONSUMPTION,
    "NIFTY SERVICES SECTOR": NIFTY_SERVICES_SECTOR,
    "NIFTY100 ESG SECTOR LEADERS": NIFTY_100_ESG_SECTOR_LEADERS,
    "NIFTY100 ESG": NIFTY_100_ESG,
    "NIFTY INDIA MANUFACTURING": NIFTY_INDIA_MANUFACTURING,
    "NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP 25% CAP": NIFTY_INDIA_CORPORATE_GROUP_TATA,
    "NIFTY500 MULTICAP INDIA MANUFACTURING 50:30:20": NIFTY_500_MULTICAP_INDIA_MANUFACTURING_50_30_20,
    "NIFTY500 MULTICAP INFRASTRUCTURE 50:30:20": NIFTY_500_MULTICAP_INFRASTRUCTURE_50_30_20,
    "NIFTY INDIA DEFENCE": NIFTY_INDIA_DEFENCE,
    "NIFTY INDIA TOURISM": NIFTY_INDIA_TOURISM,
    "NIFTY CAPITAL MARKETS": NIFTY_CAPITAL_MARKETS,
    "NIFTY EV & NEW AGE AUTOMOTIVE": NIFTY_EV_NEW_AGE_AUTOMOTIVE,
    "NIFTY INDIA NEW AGE CONSUMPTION": NIFTY_INDIA_NEW_AGE_CONSUMPTION,
    "NIFTY INDIA SELECT 5 CORPORATE GROUPS (MAATR)": NIFTY_INDIA_SELECT_5_CORPORATE_GROUPS,
    "NIFTY100 ENHANCED ESG": NIFTY_100_ENHANCED_ESG,
    "NIFTY CORE HOUSING": NIFTY_CORE_HOUSING,
    "NIFTY HOUSING": NIFTY_HOUSING,
    "NIFTY IPO": NIFTY_IPO,
    "NIFTY MIDSMALL INDIA CONSUMPTION": NIFTY_MIDSMALL_INDIA_CONSUMPTION,
    "NIFTY NON-CYCLICAL CONSUMER": NIFTY_NON_CYCLICAL_CONSUMER,
    "NIFTY RURAL": NIFTY_RURAL,
    "NIFTY SHARIAH 25": NIFTY_SHARIAH_25,
    "NIFTY TRANSPORTATION & LOGISTICS": NIFTY_TRANSPORTATION_LOGISTICS,
    "NIFTY50 SHARIAH": NIFTY_50_SHARIAH,
    "NIFTY500 SHARIAH": NIFTY_500_SHARIAH,
    "NIFTY SME EMERGE": NIFTY_SME_EMERGE,
    "NIFTY INDIA INTERNET": NIFTY_INDIA_INTERNET,
    "NIFTY WAVES": NIFTY_WAVES,
    "NIFTY INDIA INFRASTRUCTURE & LOGISTICS": NIFTY_INDIA_INFRASTRUCTURE_LOGISTICS,
    "NIFTY100 LIQUID 15": NIFTY_100,
    "NIFTY MIDCAP LIQUID 15": NIFTY_MIDCAP_50,
}

def _load_nse_cache():
    """Load NSE cache if available."""
    try:
        from pathlib import Path
        import json
        cache_file = Path("nse_universe_cache.json")
        if cache_file.exists():
            with open(cache_file, 'r') as f:
                data = json.load(f)
                return data.get('universes', {})
    except:
        pass
    return {}

def get_universe(name):
    """Get stock list for a given universe name. Uses NSE cache if available."""
    # First try NSE cache
    cached = _load_nse_cache()
    if name in cached:
        return cached[name]
    
    # Fallback to hardcoded
    return UNIVERSES.get(name, [])

def get_all_universe_names():
    """Get all available universe names. Combines NSE cache with hardcoded."""
    # Combine both sources
    cached = _load_nse_cache()
    all_names = set(UNIVERSES.keys())
    all_names.update(cached.keys())
    return sorted(list(all_names))

def get_broad_market_universes():
    """Get broad market indices."""
    return ["NIFTY 50", "NIFTY NEXT 50", "NIFTY 100", "NIFTY 200", "NIFTY 500"]

def get_sectoral_universes():
    """Get sectoral indices."""
    return [
        "NIFTY BANK", "NIFTY FINANCIAL SERVICES", "NIFTY IT", "NIFTY PHARMA",
        "NIFTY AUTO", "NIFTY FMCG", "NIFTY METAL", "NIFTY REALTY",
        "NIFTY ENERGY", "NIFTY CONSUMPTION", "NIFTY MEDIA",
        "NIFTY HEALTHCARE", "NIFTY OIL & GAS"
    ]

def get_cap_based_universes():
    """Get cap-based indices."""
    return [
        "NIFTY MIDCAP 50", "NIFTY MIDCAP 100", "NIFTY MIDCAP 150",
        "NIFTY SMALLCAP 50", "NIFTY SMALLCAP 100", "NIFTY SMALLCAP 250",
        "NIFTY MICROCAP 250"
    ]

def get_thematic_universes():
    """Get thematic indices."""
    return [
        "NIFTY PSU", "NIFTY PSU BANK", "NIFTY PRIVATE BANK", "NIFTY MNC",
        "NIFTY INFRA", "NIFTY COMMODITIES", "NIFTY CPSE",
        "NIFTY DIVIDEND OPPORTUNITIES 50", "NIFTY QUALITY 30",
        "NIFTY ALPHA 50", "NIFTY LOW VOLATILITY 30", "NIFTY MOBILITY",
        "NIFTY INDIA DIGITAL", "NIFTY CONSUMER DURABLES"
    ]
