name: Sync to HuggingFace Spaces

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://artist-23:$HF_TOKEN@huggingface.co/spaces/artist-23/investing-scanner
          git push hf main --force
